name: controlasistencia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  lucide_icons: ^0.257.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.4.5
  image_picker: ^0.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true